---
- hosts: localhost
  become: yes
  tasks:
  
  - name: Instalar Webserver Python
    apt:
      name: "{{ item }}"
      state: present
    with_items:
       - python3-pip
       - build-essential
       - libssl-dev
       - libffi-dev
       - python3-dev
       - python3-venv
       
 - name: Intalacion PIP tools
   pip:
     name: "{{ item }}"
     
   with_items:
     - setuptools
     - flask
     